# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt update
        sudo apt install ninja-build clang cmake libgtk-3-dev
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: |
        flutter config --enable-linux-desktop
        flutter update-packages
        flutter devices
        flutter doctor
      env:
        FLUTTER_ROOT: $(echo $FLUTTER_HOME)
    # - run: flutter test
    - run: flutter build linux --pub --verbose
      env:
        FLUTTER_ROOT: $(echo $FLUTTER_HOME)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/linux/release/bundle
    - name: Snapcraft Action
      uses: samuelmeuli/action-snapcraft@v1.1.2
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
